name: multiversx_sdk
description: MultiversX SDK for Dart
# version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bip39_mnemonic: ^3.0.10
  convert: ^3.1.2
  dio: ^5.8.0+1
  ed25519_hd_key: ^2.3.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  lints: ^6.0.0
  meta: ^1.17.0
  pinenacl: ^0.6.0
  pointycastle: ^4.0.0
  retrofit: ^4.7.0

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1
  test: ^1.26.3
