name: multiversx_sdk
description: MultiversX SDK for Dart
# version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip39: ^1.0.6
  convert: ^3.0.1
  dio: ^5.1.2
  ed25519_hd_key: ^2.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.4.0
  lints: ^2.1.0
  meta: ^1.7.0
  pinenacl: ^0.3.3
  pointycastle: ^3.4.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^2.3.4
  json_serializable: ^6.1.1
  retrofit_generator: ^7.0.1
  test: ^1.19.0
