name: multiversx_sdk
description: MultiversX SDK for Dart
# version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip39: ^1.0.6
  convert: ^3.1.1
  dio: ^5.3.2
  ed25519_hd_key: ^2.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  lints: ^2.1.1
  meta: ^1.10.0
  pinenacl: ^0.5.1
  pointycastle: ^3.7.3
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.0
  test: ^1.24.6
